services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASSWORD}
      - INFLUXDB_DB=gnss_monitor
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data: